//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test4
{
    using System;
    using System.Collections.Generic;
    
    public partial class phongvienthuongtru
    {
        public string Manv { get; set; }
        public Nullable<double> Phucap { get; set; }
    
        public virtual x thongtinphongvien { get; set; }
    }
}
