//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test4
{
    using System;
    using System.Collections.Generic;
    
    public partial class x
    {
        public string Manv { get; set; }
        public string Hoten { get; set; }
        public string Gioitinh { get; set; }
        public string Dienthoai { get; set; }
        public Nullable<System.DateTime> Ngayvaolam { get; set; }
    
        public virtual phongvientaitoasoan phongvientaitoasoan { get; set; }
        public virtual phongvienthuongtru phongvienthuongtru { get; set; }
    }
}
